

spring:
  application:
    name: backend

  profiles:
    active: local

  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vtp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.uestc.group14.vtpbackend.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: your-256-bit-secret-key-change-this-in-production-environment-must-be-256-bit
  expiration: 86400000  # 24小时（毫秒）